// Curated list of common countries for the onboarding picker. Stored as the
// human-readable label since the DB column accepts free text up to 60 chars.
// "United States" is duplicated at the top so it shows up first without
// scrolling — feel free to drop the duplicate if your audience is global.

export const COUNTRIES = [
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Ireland',
  'Portugal',
  'Austria',
  'Poland',
  'Czechia',
  'Greece',
  'Mexico',
  'Brazil',
  'Argentina',
  'Chile',
  'Colombia',
  'Japan',
  'South Korea',
  'Singapore',
  'Hong Kong',
  'Taiwan',
  'India',
  'United Arab Emirates',
  'Saudi Arabia',
  'Israel',
  'South Africa',
  'New Zealand',
  'Other',
] as const;
